revert SVN commit 849074 by dhaumann: because this is what is needed to compile against the trunk/kdesupport/strigi
fix compile:
kdelibs/kio/kio/dummyanalyzers/dummyanalyzers.cpp:43: error: conflicting return type specified for ‘virtual char DummyEndAnalyzer::analyze(Strigi::AnalysisResult&, Strigi::InputStream*)’
/home/dh/kde/run/kde4/include/strigi/streamendanalyzer.h:37: error:   overriding ‘virtual signed char Strigi::StreamEndAnalyzer::analyze(Strigi::AnalysisResult&, Strigi::InputStream




git-svn-id: svn+ssh://svn.kde.org/home/kde/trunk/KDE/kdelibs@849105 283d02a7-25f6-0310-bc7c-ecb5cbfe19da